post http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFudGVyb3ZpcHVuZW4iLCJpZCI6IjVkOWRlYzExMmY1YzBmMDJkMGRhOTE2MiIsImlhdCI6MTU3MDY0MDAyM30.T5DTQjuT2cOqpy0NwV2OSV1fgMuAEy3GaIzwn2exV40

{
    "title": "new cool blog",
    "author": "Kurt Gödel",
    "url":  "logicguy",
    "likes": 5
}